"""workflow_automation_columns

Revision ID: 5ace12fa5334
Revises: 9961ae4a6d9e
Create Date: 2026-03-17 17:25:26.094216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ace12fa5334'
down_revision: Union[str, None] = '9961ae4a6d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent SQL protects local/dev databases with partial schema drift.
    op.execute("ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS invoice_id INTEGER")
    op.execute("ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS client_id INTEGER")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'bank_transactions_client_id_fkey'
            ) THEN
                ALTER TABLE bank_transactions
                ADD CONSTRAINT bank_transactions_client_id_fkey
                FOREIGN KEY (client_id) REFERENCES clients (id);
            END IF;
        END$$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'bank_transactions_invoice_id_fkey'
            ) THEN
                ALTER TABLE bank_transactions
                ADD CONSTRAINT bank_transactions_invoice_id_fkey
                FOREIGN KEY (invoice_id) REFERENCES invoices (id);
            END IF;
        END$$;
        """
    )
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS job_id INTEGER")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS trip_id INTEGER")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS last_payment_at TIMESTAMP")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'invoices_job_id_fkey'
            ) THEN
                ALTER TABLE invoices
                ADD CONSTRAINT invoices_job_id_fkey
                FOREIGN KEY (job_id) REFERENCES jobs (id);
            END IF;
        END$$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'invoices_trip_id_fkey'
            ) THEN
                ALTER TABLE invoices
                ADD CONSTRAINT invoices_trip_id_fkey
                FOREIGN KEY (trip_id) REFERENCES trips (id);
            END IF;
        END$$;
        """
    )
    op.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS latest_eway_bill_number VARCHAR(50)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'latest_eway_bill_number')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'last_payment_at')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'auto_generated')
    op.drop_column('invoices', 'trip_id')
    op.drop_column('invoices', 'job_id')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'client_id')
    op.drop_column('bank_transactions', 'invoice_id')
    # ### end Alembic commands ###
