"""workflow_automation_columns

Revision ID: 5ace12fa5334
Revises: 9961ae4a6d9e
Create Date: 2026-03-17 17:25:26.094216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ace12fa5334'
down_revision: Union[str, None] = '9961ae4a6d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.add_column('bank_transactions', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bank_transactions', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'bank_transactions', 'invoices', ['invoice_id'], ['id'])
    op.add_column('invoices', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('auto_generated', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('last_payment_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'trips', ['trip_id'], ['id'])
    op.add_column('jobs', sa.Column('latest_eway_bill_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'latest_eway_bill_number')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'last_payment_at')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'auto_generated')
    op.drop_column('invoices', 'trip_id')
    op.drop_column('invoices', 'job_id')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'client_id')
    op.drop_column('bank_transactions', 'invoice_id')
    # ### end Alembic commands ###
