"""add_fuel_pump_tables_and_pump_operator_role

Revision ID: 9961ae4a6d9e
Revises: 57d811c868b8
Create Date: 2026-03-17 16:26:06.006097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9961ae4a6d9e'
down_revision: Union[str, None] = '57d811c868b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
