"""add_security_pin_hash_to_drivers

Revision ID: b689434ea2ec
Revises: b007
Create Date: 2026-03-20 15:42:06.583999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b689434ea2ec'
down_revision: Union[str, None] = 'b007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_queue_client_action_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_status'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_user_id'), table_name='sync_queue')
    op.drop_table('sync_queue')
    op.drop_column('bank_accounts', 'opening_balance_paise')
    op.drop_column('bank_accounts', 'alert_threshold_paise')
    op.drop_index(op.f('idx_csv_txn_import'), table_name='bank_csv_transactions')
    op.alter_column('banking_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('banking_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('banking_entries', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('banking_entries', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_banking_entry_account_date'), table_name='banking_entries')
    op.create_index(op.f('ix_banking_entries_id'), 'banking_entries', ['id'], unique=False)
    op.add_column('drivers', sa.Column('security_pin_hash', sa.String(length=128), nullable=True))
    op.drop_index(op.f('idx_ewb_valid_upto'), table_name='eway_bills')
    op.alter_column('trip_expenses', 'biometric_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('vehicle_maintenance', sa.Column('workshop_id', sa.Integer(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('work_order_number', sa.String(length=50), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('parts_description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'vehicle_maintenance', 'workshops', ['workshop_id'], ['id'])
    op.add_column('vehicle_tyres', sa.Column('retread_count', sa.Integer(), nullable=True))
    op.add_column('vehicle_tyres', sa.Column('max_retreads', sa.Integer(), nullable=True))
    op.add_column('vehicle_tyres', sa.Column('last_retread_date', sa.Date(), nullable=True))
    op.add_column('vehicle_tyres', sa.Column('total_retread_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_tyres', 'total_retread_cost')
    op.drop_column('vehicle_tyres', 'last_retread_date')
    op.drop_column('vehicle_tyres', 'max_retreads')
    op.drop_column('vehicle_tyres', 'retread_count')
    op.drop_constraint(None, 'vehicle_maintenance', type_='foreignkey')
    op.drop_column('vehicle_maintenance', 'parts_description')
    op.drop_column('vehicle_maintenance', 'work_order_number')
    op.drop_column('vehicle_maintenance', 'workshop_id')
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('trip_expenses', 'biometric_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_ewb_valid_upto'), 'eway_bills', ['valid_until'], unique=False)
    op.drop_column('drivers', 'security_pin_hash')
    op.drop_index(op.f('ix_banking_entries_id'), table_name='banking_entries')
    op.create_index(op.f('idx_banking_entry_account_date'), 'banking_entries', ['account_id', 'entry_date'], unique=False)
    op.alter_column('banking_entries', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('banking_entries', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('banking_entries', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('banking_entries', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_csv_txn_import'), 'bank_csv_transactions', ['import_id', 'match_status'], unique=False)
    op.add_column('bank_accounts', sa.Column('alert_threshold_paise', sa.BIGINT(), server_default=sa.text("'500000'::bigint"), autoincrement=False, nullable=True))
    op.add_column('bank_accounts', sa.Column('opening_balance_paise', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    op.create_table('sync_queue',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('action_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('action_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('client_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('client_action_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CONFLICT', name='syncactionstatus'), autoincrement=False, nullable=False),
    sa.Column('server_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('sync_queue_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sync_queue_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_queue_pkey'))
    )
    op.create_index(op.f('ix_sync_queue_user_id'), 'sync_queue', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_status'), 'sync_queue', ['status'], unique=False)
    op.create_index(op.f('ix_sync_queue_id'), 'sync_queue', ['id'], unique=False)
    op.create_index(op.f('ix_sync_queue_client_action_id'), 'sync_queue', ['client_action_id'], unique=False)
    # ### end Alembic commands ###
